services:
  marytts:
    build:
      context: ./marytts
      dockerfile: Dockerfile
    image: my-marytts
    container_name: marytts
    ports:
      - "59125:59125"
    restart: unless-stopped

  opentts:
    build:
      context: ./opentts
      dockerfile: Dockerfile
    image: my-opentts
    container_name: opentts
    ports:
      - "5500:5500"
    depends_on:
      - marytts
    command: >
      python3 app.py
        --host 0.0.0.0
        --port 5500
        --marytts-url http://marytts:59125
    restart: unless-stopped
