services:
  opentts:
    image: synesthesiam/opentts:arm64
    ports:
      - 5500:5500
    command: --marytts-url http://marytts:59125 --mozillatts-url http://mozillatts:5002
    tty: true
    depends_on:
      - marytts
      - mozillatts

  marytts:
    image: synesthesiam/marytts:5.2-arm64
    tty: true

  mozillatts:
    image: synesthesiam/mozilla-tts:arm64
    tty: true
