services:

  # ────────────────
  marytts:
    build:
      context: ./marytts
      dockerfile: Dockerfile
    image: my-marytts
    container_name: marytts
    ports:
      - '59125:59125'
    restart: unless-stopped

  # ────────────────
  # Mozilla-TTS service (mozillatts)
  # ────────────────
  # mozillatts:
  #   build:
  #     context: ./mozillatts
  #     dockerfile: Dockerfile
  #   image: my-mozillatts
  #   container_name: mozillatts
  #   ports:
  #     - '5002:5002'
  #   restart: unless-stopped

  # ────────────────
  # OpenTTS service
  # ────────────────
  opentts:
    build:
      context: ./opentts
      dockerfile: Dockerfile
    image: my-opentts
    container_name: opentts
    ports:
      - '5500:5500'
    command:
      - python3
      - app.py
      - --marytts-url
      - http://marytts:59125
      - --mozillatts-url
      - http://mozillatts:5002
    restart: unless-stopped